# site settings
# access via {{ site.name }}
name: Mayur Dave
author: Mayur Dave
title: mdave16
description: Personal website of Mayur Dave
url: http://mdave16.github.io
avatar: https://avatars.githubusercontent.com/mdave16
twitter: mdave248
email: mdave3927@gmail.com
rss: feed.xml

author:
  twitter: mdave248
  github: mdave16
  stackoverflow: 4400874/mdave16
  linkedin: mayur-dave-b058179a

permalink: /blog/:year/:month/:day/:title

# build settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
