# site settings
# access via {{ site.name }}
name: Mayur Dave
author: Mayur Dave
title: mdave16
description: A bunch of stuff that I think is cool!
url: http://mdave16.github.io
avatar: https://avatars.githubusercontent.com/mdave16
twitter: mdave248
email: mdave3927@gmail.com
github: mdave16
linkedin: mayur-dave-b058179a
stackoverflow: users/4400874/mdave16
rss: feed.xml

author:
  twitter: mdave248

permalink: /blog/:year/:month/:day/:title

# build settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
