name: Mayur Dave
title: Mayur Dave
tagline: Personal website of Mayur Dave
description: Personal website of Mayur Dave, software engineer who enjoys maths and board games.
url: http://mdave16.github.io
baseurl: ''
repository: mdave16/mdave16.github.io
avatar: https://avatars.githubusercontent.com/mdave16
twitter:
  username: mdave248
email: mdave3927@gmail.com
github: mdave16
linkedin: mayur-dave-b058179a
stackoverflow: users/4400874/mdave16
logo: /assets/images/tree.ico
social:
  name: Mayur Dave
  links:
    - https://twitter.com/mdave248
    - https://www.linkedin.com/in/mayur-dave-b058179a
    - https://github.com/mdave16
    - https://stackoverflow.com/users/4400874/mdave16
author:
  twitter: mdave248
locale: en_GB
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blogpost"
# build settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"

collections:
  side_projects:
    output: true
    permalink: :path
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

side_projects:
  - /crpytography
  - /stunning-bassoon

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

uncss:
  stylesheets:
    - assets/css/blog.css
    - assets/css/main.css
    - assets/css/skeleton.css
  files:
    - "**/*.html"
    - "**/*.md"
  compress: true
  banner: true